### ISSUE TITLE
topic word to create word cloud

### ISSUE THREAD

**Issue by pistis** [pistis/iroun#1]
# purpose
- [x] Extract Topic Word (using TF-IDF text mining) , a.k.a analyzeTopicWords

# tasks
- [x] parse source code @ref https://github.com/fkling/astexplorer
  - [x] parse vue component
  - [x] parse flow script
  - [x] parse typescript
  - [x] parse jsx
- [x] Analyze 13 javascript-based projects that have received many star of [github](https://github.com/trending/javascript?since=monthly)
  - [x] Analyze name extraction / frequency
  - [x] Separate names by word (by frequency)
  - [x] Filter stopword from word list
    - [x] Do I have to filter out customary words?
  - [x] Saving structured data of this information as a text-based file
  - [x] Automatically create final word list file by typing github address
  - [x] filter only noun word
- [x] Analyze 100 javascript-based projects that have received many star of [github]
  - [x] download most star js github project 100 by script
- [x] Make topic word cloud image
  - [x] extract topic word list by specific top 100 project (using TF-IDF text mining)
  - [x] make guide for word cloud image file(png)
  - [x] support cli 
    - [x] [commander.js](https://github.com/tj/commander.js)
    - [x] Refactoring scripts for publish.
- [x] Prepare publish
  - [x] Modifying README.md
  - [x] versioning v0.2.0
  - [x] publish npm
